### ISSUE TITLE
ALL JOBS WONT DISPLAY AND CANT EDIT / CREATE GRADES AND CAN'T ALLOW CERTAIN THINGS LIKE CUFFING OR BILLING

### ISSUE THREAD

**Issue by lyoneofficial** [polisek/pls_jobsystem#3]
ALL JOBS WONT DISPLAY AND CANT EDIT / CREATE GRADES AND CAN'T ALLOW CERTAIN THINGS LIKE CUFFING OR BILLING

**Comment by polisek** [comment]
Nowhere is it absolutely stated that it should create new grads and jobs.
If you want, you can find how to create a grade directly with a job on doc.polisek.io documentation.

Nowhere in the video or in the description of the script is it stated that it should create a job in the database or possibly at the QB in the config.
For billing use your own script via export or the same as bossmenu.

**Comment by lyoneofficial** [comment]
I use esx

**Comment by lyoneofficial** [comment]
just one job
